force-app/main/default/objects/Conference__c/Conference__c.object-meta.xml
<CustomObject>
    <description>Maintain all the conference data</description>
    <label>Conference</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conference__c/fields/Conference_Description__c.field-meta.xml
<CustomField>
    <fullName>Conference_Description__c</fullName>
    <description>Add conference detail information.</description>
    <inlineHelpText>Enter Conference description</inlineHelpText>
    <label>Session Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Conference_Duration__c.field-meta.xml
<CustomField>
    <fullName>Conference_Duration__c</fullName>
    <inlineHelpText>Select Duration</inlineHelpText>
    <label>Session Duration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>30 Min</fullName>
            </value>
            <value>
                <fullName>1 to 2 hr</fullName>
            </value>
            <value>
                <fullName>2 to 3 hr</fullName>
            </value>
            <value>
                <fullName>45 Min</fullName>
            </value>
            <value>
                <fullName>60 Min</fullName>
            </value>
            <value>
                <fullName>90 Min</fullName>
            </value>
            <value>
                <fullName>120 Min</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Conference_Room__c.field-meta.xml
<CustomField>
    <fullName>Conference_Room__c</fullName>
    <description>All conference location</description>
    <inlineHelpText>Enter conference location</inlineHelpText>
    <label>Session Room</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Auditorium</fullName>
                <default>true</default>
                <label>Auditorium</label>
            </value>
            <value>
                <fullName>Breakout room A</fullName>
            </value>
            <value>
                <fullName>Breakout room B</fullName>
            </value>
            <value>
                <fullName>Bоаrdrооm</fullName>
            </value>
            <value>
                <fullName>Keynote room</fullName>
            </value>
            <value>
                <fullName>Theater</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Conference_Time__c.field-meta.xml
<CustomField>
    <fullName>Conference_Time__c</fullName>
    <description>Add conference time</description>
    <inlineHelpText>Enter Session Date and Time</inlineHelpText>
    <label>Session Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Conference_Topic__c.field-meta.xml
<CustomField>
    <fullName>Conference_Topic__c</fullName>
    <label>Conference Topic</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Picture_Path__c.field-meta.xml
<CustomField>
    <fullName>Picture_Path__c</fullName>
    <description>speaker photo URL</description>
    <label>Picture Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Conference_SOQL.cls
/********************************************************************************
         * Date 	        ||	Author				||	Description
         * 18-Sept-2021		||	Harshal Kolhe		|| 	Created.
    *******************************************************************************/

public with sharing class Conference_SOQL {

    /*
     *Apex ClassName : Conference_SOQL
     *Aped MethodName: getContactList
     *Desc			 : Create constant method , which return the list of SObject.
     *Parameters     : Object list Id's.
     *Return type    : list<Sobject>
     *Author		 : Harshal Kolhe.
     *Created Date	 : 18/09/2021
     */
    public static List < Contact > getContactList(List<Id> contactIdList) {
        
        List < Contact > listContact = [SELECT Id,Name,Picture_Path__c,Email
                                       FROM Contact
                                       WHERE Id IN : contactIdList 
                                       WITH SECURITY_ENFORCED
        ];
        return listContact;
    }

    /*
     *Apex ClassName : Conference_SOQL
     *Aped MethodName: getConferenceList
     *Desc			 : Create constant method , which return the list of SObject.
     *Parameters     : Object list Id's.
     *Return type    : list<Sobject>
     *Author		 : Harshal Kolhe.
     *Created Date	 : 18/09/2021
     */
    public static List < Conference__c > getConferenceList(List<Id> conferenceIdList) {
        
        List < Conference__c > listConference = [SELECT Id,Name,Conference_Time__c,Conference_Duration__c,Conference_Room__c,
                                                    Conference_Topic__c,Conference_Description__c,Level__c
                                            FROM Conference__c
                                            WHERE Id IN : conferenceIdList 
                                            WITH SECURITY_ENFORCED
        ];
        return listConference;
    }    
}